services:
  vibevoice:
    image: fhrozen/vibevoice:latest
    build:
      context: .
      dockerfile: ./dev.dockerfile
      args:
        - TAG=fhrozen/python-root
    volumes:
      - ./models:/root/.cache/huggingface
      - ./VibeVoice/demo:/workspace/VibeVoice/demo
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
